"""new

Revision ID: 34dfdc7f4d16
Revises: c22196f6f43a
Create Date: 2024-06-08 17:02:16.632623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34dfdc7f4d16'
down_revision = 'c22196f6f43a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
