"""some_new

Revision ID: 3b3e614dc1c4
Revises: 34dfdc7f4d16
Create Date: 2024-06-08 17:08:08.179678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3e614dc1c4'
down_revision = '34dfdc7f4d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
