"""some

Revision ID: 560aa571c61f
Revises: 3b3e614dc1c4
Create Date: 2024-06-09 00:37:10.324886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560aa571c61f'
down_revision = '3b3e614dc1c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualification_competencies', sa.Column('competence_id', sa.UUID(as_uuid=False), nullable=False))
    op.drop_constraint('qualification_competencies_competencies_id_fkey', 'qualification_competencies', type_='foreignkey')
    op.create_foreign_key(None, 'qualification_competencies', 'competencies', ['competence_id'], ['id'])
    op.drop_column('qualification_competencies', 'competencies_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualification_competencies', sa.Column('competencies_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'qualification_competencies', type_='foreignkey')
    op.create_foreign_key('qualification_competencies_competencies_id_fkey', 'qualification_competencies', 'competencies', ['competencies_id'], ['id'])
    op.drop_column('qualification_competencies', 'competence_id')
    # ### end Alembic commands ###
