"""some

Revision ID: 98e063f9bc28
Revises: f6f64fa700f6
Create Date: 2024-06-08 16:44:20.865682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e063f9bc28'
down_revision = 'f6f64fa700f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exams_group_id_fkey', 'exams', type_='foreignkey')
    op.drop_constraint('exams_teacher_id_fkey', 'exams', type_='foreignkey')
    op.drop_constraint('exams_discipline_id_fkey', 'exams', type_='foreignkey')
    op.create_foreign_key(None, 'exams', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exams', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exams', 'disciplines', ['discipline_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('group_students_group_id_fkey', 'group_students', type_='foreignkey')
    op.drop_constraint('group_students_student_id_fkey', 'group_students', type_='foreignkey')
    op.create_foreign_key(None, 'group_students', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_students', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('groups_qualification_id_fkey', 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'qualifications', ['qualification_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('qualification_exams_group_id_fkey', 'qualification_exams', type_='foreignkey')
    op.drop_constraint('qualification_exams_teacher_id_fkey', 'qualification_exams', type_='foreignkey')
    op.drop_constraint('qualification_exams_discipline_id_fkey', 'qualification_exams', type_='foreignkey')
    op.create_foreign_key(None, 'qualification_exams', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'qualification_exams', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'qualification_exams', 'disciplines', ['discipline_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('qualification_exams_members_commission_member_id_fkey', 'qualification_exams_members', type_='foreignkey')
    op.drop_constraint('qualification_exams_members_qualification_exam_id_fkey', 'qualification_exams_members', type_='foreignkey')
    op.create_foreign_key(None, 'qualification_exams_members', 'qualification_commission_members', ['commission_member_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'qualification_exams_members', 'qualification_exams', ['qualification_exam_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('questions_theme_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'themes', ['theme_id'], ['id'], ondelete='CASCADE')
    op.add_column('themes', sa.Column('exam_id', sa.UUID(as_uuid=False), nullable=False))
    op.drop_constraint('themes_discipline_id_fkey', 'themes', type_='foreignkey')
    op.create_foreign_key(None, 'themes', 'exams', ['exam_id'], ['id'], ondelete='CASCADE')
    op.drop_column('themes', 'discipline_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('discipline_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'themes', type_='foreignkey')
    op.create_foreign_key('themes_discipline_id_fkey', 'themes', 'disciplines', ['discipline_id'], ['id'])
    op.drop_column('themes', 'exam_id')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_theme_id_fkey', 'questions', 'themes', ['theme_id'], ['id'])
    op.drop_constraint(None, 'qualification_exams_members', type_='foreignkey')
    op.drop_constraint(None, 'qualification_exams_members', type_='foreignkey')
    op.create_foreign_key('qualification_exams_members_qualification_exam_id_fkey', 'qualification_exams_members', 'qualification_exams', ['qualification_exam_id'], ['id'])
    op.create_foreign_key('qualification_exams_members_commission_member_id_fkey', 'qualification_exams_members', 'qualification_commission_members', ['commission_member_id'], ['id'])
    op.drop_constraint(None, 'qualification_exams', type_='foreignkey')
    op.drop_constraint(None, 'qualification_exams', type_='foreignkey')
    op.drop_constraint(None, 'qualification_exams', type_='foreignkey')
    op.create_foreign_key('qualification_exams_discipline_id_fkey', 'qualification_exams', 'disciplines', ['discipline_id'], ['id'])
    op.create_foreign_key('qualification_exams_teacher_id_fkey', 'qualification_exams', 'users', ['teacher_id'], ['id'])
    op.create_foreign_key('qualification_exams_group_id_fkey', 'qualification_exams', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key('groups_qualification_id_fkey', 'groups', 'qualifications', ['qualification_id'], ['id'])
    op.drop_constraint(None, 'group_students', type_='foreignkey')
    op.drop_constraint(None, 'group_students', type_='foreignkey')
    op.create_foreign_key('group_students_student_id_fkey', 'group_students', 'users', ['student_id'], ['id'])
    op.create_foreign_key('group_students_group_id_fkey', 'group_students', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.create_foreign_key('exams_discipline_id_fkey', 'exams', 'disciplines', ['discipline_id'], ['id'])
    op.create_foreign_key('exams_teacher_id_fkey', 'exams', 'users', ['teacher_id'], ['id'])
    op.create_foreign_key('exams_group_id_fkey', 'exams', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
