"""new

Revision ID: b697b8453016
Revises: 4b062738aee6
Create Date: 2024-02-21 13:26:10.946063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b697b8453016'
down_revision = '4b062738aee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'patronymic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'patronymic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
