"""new

Revision ID: c22196f6f43a
Revises: 98e063f9bc28
Create Date: 2024-06-08 17:00:01.791584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22196f6f43a'
down_revision = '98e063f9bc28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
