"""update

Revision ID: f6f64fa700f6
Revises: b697b8453016
Create Date: 2024-02-21 13:29:59.367381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f64fa700f6'
down_revision = 'b697b8453016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qualification_commission_members', 'patronymic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qualification_commission_members', 'patronymic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
