from .users import UserModel
from .exams import ExamModel
from .qualification_exams import QualificationExamModel
from .qualifications import QualificationModel
from .qualification_competencies import QualificationCompetenceModel
from .competencies import CompetenceModel
from .qualification_exams_members import QualificationExamsMemberModel
from .qualification_commission_members import QualificationCommissionMemberModel
from .disciplines import DisciplineModel
from .groups import GroupModel
from .group_students import GroupStudentModel
from .themes import ThemeModel
from .questions import QuestionModel
