from .users import UserModel
from .exams import ExamModel
from .qualifications import QualificationModel
from .qualification_competencies import QualificationCompetenceModel
from .competencies import CompetenceModel
from .disciplines import DisciplineModel
from .groups import GroupModel
from .group_students import GroupStudentModel
from .themes import ThemeModel
from .questions import QuestionModel
from .graduate_theses import GraduateThesisModel
from .course_works import CourseWorkModel
from .educational_practices import EducationalPracticeModel
