from .create import CreateGraduateThesisHandler
from .delete import DeleteGraduateThesisHandler
from .get import GetGraduateThesisHandler, GetGraduateThesisListHandler, GetGraduateThesisListByGroupHandler
from .update import UpdateGraduateThesisHandler
