from .create import CreateGraduateThesisRequest
from .delete import DeleteGraduateThesisRequest
from .get import GetGraduateThesisRequest, GetGraduateThesisListRequest, GetGraduateThesisListByGroupRequest
from .update import UpdateGraduateThesisRequest
