from .users import *
from .themes import *
from .questions import *
from .qualifications import *
from .qualification_competencies import *
from .groups import *
from .group_students import *
from .exams import *
from .disciplines import *
from .competencies import *
from .graduate_theses import *
from .course_works import *
from .educational_practices import *
