from .users import UserDomainEntity
from .competencies import CompetenceDomainEntity
from .disciplines import DisciplineDomainEntity
from .exams import ExamDomainEntity
from .group_students import GroupStudentDomainEntity
from .qualifications import QualificationDomainEntity
from .groups import GroupDomainEntity
from .qualification_competencies import QualificationCompetenceDomainEntity
from .themes import ThemeDomainEntity
from .questions import QuestionDomainEntity
from .graduate_theses import GraduateThesisDomainEntity
from .course_works import CourseWorkDomainEntity
from .educational_practices import EducationalPracticeDomainEntity
