from .users import UserRepository
from .exams import ExamRepository
from .qualifications import QualificationRepository
from .qualification_competencies import QualificationCompetenceRepository
from .competencies import CompetenceRepository
from .disciplines import DisciplineRepository
from .groups import GroupRepository
from .group_students import GroupStudentRepository
from .themes import ThemeRepository
from .questions import QuestionRepository
from .course_works import CourseWorkRepository
from .graduate_theses import GraduateThesisRepository
from .educational_practicies import EducationalPracticeRepository
